name: badlion_plugin_config
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.7

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  json_serializable: ^6.7.1
  lints: ^2.0.0
